/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import controller.DocTien;
import dao.DAO_Thuoc;
import entity.CT_HoaDonBan;
import entity.HoaDonBan;
import entity.KhachHang;
import entity.NhanVien;

/**
 *
 * @author HoangPC
 */
public class ChitietHoadonBanJframe extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DAO_Thuoc daoBanthuoc = new DAO_Thuoc();
	private String maHd;
	private int i;

	/** Creates new form ThemKHJframe */
	// goi chi tiet hoa don dung ma hoa don
	public ChitietHoadonBanJframe(String maHd) {
		initComponents();
		tblCtHD.getColumnModel().getColumn(2).setPreferredWidth(5);
		setLocationRelativeTo(null);
		this.maHd = maHd;
		docVaoChiTiet();
		docDataCtBanVaoTable();
		tinhTongTienHD();
		tinhTongTienVat();
		tinhTongTien();
	}

	public ChitietHoadonBanJframe() {
		initComponents();
		tblCtHD.getColumnModel().getColumn(2).setPreferredWidth(5);
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		lblDramacity = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtTenNV = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtGioiTinh = new javax.swing.JLabel();
		txtDC = new javax.swing.JLabel();
		txtMaHd = new javax.swing.JLabel();
		txtNgayLap = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		txtTenkh = new javax.swing.JLabel();
		lblTitle = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblCtHD = new javax.swing.JTable();
		jPanel5 = new javax.swing.JPanel();
		btnDong = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		txtTongHD = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		txtTongVAT = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		txtTongTien = new javax.swing.JLabel();
		txtTienBangChu = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Hóa đơn bán lẻ");
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		lblDramacity.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		lblDramacity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		lblDramacity.setText("NHÀ THUỐC DRAMACITY");
		lblDramacity.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel8.setText("Địa chỉ: 12 Nguyễn Văn Bảo, Phường 5, quận Gò Vấp");
		jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel11.setText("Điện thoại: 0909789241");
		jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblDramacity, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
								.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addContainerGap(13, Short.MAX_VALUE)
								.addComponent(lblDramacity)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(16, 16, 16)));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));

		jPanel6.setBackground(new java.awt.Color(255, 255, 255));

		jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel6.setText("Nhân viên:");

		jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel2.setText("Địa chỉ:");

		txtTenNV.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
		txtTenNV.setToolTipText("");

		jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel4.setText("Giới tính:");

		txtGioiTinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

		txtDC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

		txtMaHd.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
		txtMaHd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

		txtNgayLap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtNgayLap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

		jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel13.setText("Ngày lập:");

		jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel9.setText("Khách hàng:");

		txtTenkh.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
		txtTenkh.setToolTipText("");

		lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitle.setText("HÓA ĐƠN BÁN LẺ");

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		tblCtHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		tblCtHD.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, "L-Aspase 10.000IU", null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null } },
				new String[] { "STT", "Tên thuốc", "Giá", "Thành phần", "VAT", "SL", "Tổng" }) {
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class, java.lang.Double.class,
					java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class };
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tblCtHD.setEnabled(false);
		tblCtHD.setFocusable(false);
		tblCtHD.setGridColor(new java.awt.Color(0, 0, 0));
		tblCtHD.setRowHeight(25);
		tblCtHD.setShowHorizontalLines(false);
		tblCtHD.setShowVerticalLines(false);
		tblCtHD.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(tblCtHD);
		if (tblCtHD.getColumnModel().getColumnCount() > 0) {
			tblCtHD.getColumnModel().getColumn(0).setResizable(false);
			tblCtHD.getColumnModel().getColumn(0).setPreferredWidth(10);
			tblCtHD.getColumnModel().getColumn(1).setResizable(false);
			tblCtHD.getColumnModel().getColumn(1).setPreferredWidth(200);
			tblCtHD.getColumnModel().getColumn(2).setResizable(false);
			tblCtHD.getColumnModel().getColumn(2).setPreferredWidth(5);
			tblCtHD.getColumnModel().getColumn(3).setResizable(false);
			tblCtHD.getColumnModel().getColumn(3).setPreferredWidth(230);
			tblCtHD.getColumnModel().getColumn(4).setResizable(false);
			tblCtHD.getColumnModel().getColumn(4).setPreferredWidth(5);
			tblCtHD.getColumnModel().getColumn(5).setResizable(false);
			tblCtHD.getColumnModel().getColumn(5).setPreferredWidth(5);
			tblCtHD.getColumnModel().getColumn(6).setResizable(false);
			tblCtHD.getColumnModel().getColumn(6).setPreferredWidth(60);
		}

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(jPanel6Layout.createSequentialGroup().addGap(39, 39, 39)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtTenkh, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
								.addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel6Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout
										.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtMaHd, javax.swing.GroupLayout.PREFERRED_SIZE, 181,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel6Layout.createSequentialGroup().addComponent(jLabel13)
														.addGap(18, 18, 18).addComponent(txtNgayLap,
																javax.swing.GroupLayout.PREFERRED_SIZE, 102,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGap(39, 39, 39))
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1)
						.addContainerGap()));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
						.addComponent(lblTitle).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(txtMaHd, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel6Layout.createSequentialGroup()
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel6Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(txtGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
																30, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel6Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(jPanel6Layout.createSequentialGroup()
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtTenkh, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));

		btnDong.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		btnDong.setText("Đóng");
		btnDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnDong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDongActionPerformed(evt);
			}
		});

		jPanel7.setBackground(new java.awt.Color(255, 255, 255));

		jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		jLabel3.setText("Tổng toa:");

		txtTongHD.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
		txtTongHD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

		jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		jLabel10.setText("Tổng VAT:");

		txtTongVAT.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
		txtTongVAT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

		jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		jLabel12.setText("Tổng tiền:");

		txtTongTien.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
		txtTongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup()
						.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(txtTongHD,
								javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel7Layout.createSequentialGroup()
						.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(txtTongVAT,
								javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel7Layout.createSequentialGroup()
						.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(txtTongTien,
								javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup()
						.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtTongVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))));

		txtTienBangChu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		txtTienBangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

		jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		jLabel5.setText("Bằng chữ:");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup()
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel5Layout.createSequentialGroup().addGap(0, 0, 0).addComponent(
														btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
												.addComponent(jLabel5).addGap(18, 18, 18)
												.addComponent(txtTienBangChu, javax.swing.GroupLayout.PREFERRED_SIZE,
														388, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(txtTienBangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(27, 27, 27).addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(20, 20, 20)));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0).addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel4,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel4,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0).addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChitietHoadonBanJframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChitietHoadonBanJframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChitietHoadonBanJframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChitietHoadonBanJframe.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChitietHoadonBanJframe().setVisible(true);
			}
		});
	}

	private void docVaoChiTiet() {
		KhachHang kh = daoBanthuoc.layThongtinKhachhang(maHd);
		NhanVien nv = daoBanthuoc.layThongtinNhanvien(maHd);
		HoaDonBan hdb = daoBanthuoc.getHdban(maHd);
		txtTenNV.setText(nv.getTenNV());
		txtTenkh.setText(kh.getTenKhachHang());
		txtNgayLap.setText(hdb.getNgayLapHDBan().toString());
		txtDC.setText(kh.getDiaChi().getTinhTP());
		txtMaHd.setText(maHd);
		txtGioiTinh.setText(kh.isGioiTinh() == true ? "Nam" : "Nữ");
	}

	private void docDataCtBanVaoTable() {
		List<CT_HoaDonBan> list = daoBanthuoc.getCtHdBan(maHd);
		DefaultTableModel md = (DefaultTableModel) tblCtHD.getModel();
		md.getDataVector().removeAllElements();
		list.forEach(t -> {
			i++;
			md.addRow(new Object[] { i, t.getThuoc().getTenThuoc(), t.getThuoc().getGiaBan(),
					t.getThuoc().getThanhPhan(), t.getThuoc().getThueVAT(), t.getSoLuong(),
					Math.round(t.getGiaBan() * (1 + t.getVat()) * t.getSoLuong()) });
		});
	}

	private void tinhTongTienHD() {
		int count = tblCtHD.getRowCount();
		long tongTien = 0l;
		for (int j = 0; j < count; j++) {
			tongTien += Double.parseDouble(tblCtHD.getValueAt(j, 2).toString())
					* Double.parseDouble(tblCtHD.getValueAt(j, 5).toString());
		}
		txtTongHD.setText(String.valueOf(tongTien));
	}

	private void tinhTongTienVat() {
		int count = tblCtHD.getRowCount();
		long tongTien = 0;
		for (int j = 0; j < count; j++) {
			tongTien += Double.parseDouble(tblCtHD.getValueAt(j, 2).toString())
					* Double.parseDouble(tblCtHD.getValueAt(j, 5).toString())
					* Double.parseDouble(tblCtHD.getValueAt(j, 4).toString());
		}
		txtTongVAT.setText(String.valueOf(tongTien));
	}

	private void tinhTongTien() {
		int count = tblCtHD.getRowCount();
		long tongTien = 0;
		for (int j = 0; j < count; j++) {
			tongTien += Double.parseDouble(tblCtHD.getValueAt(j, 6).toString());
		}
		txtTongTien.setText(String.valueOf(tongTien));
		DocTien read = new DocTien();
		txtTienBangChu.setText(read.readMoney(String.valueOf(tongTien)));
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnDong;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblDramacity;
	private javax.swing.JLabel lblTitle;
	private javax.swing.JTable tblCtHD;
	private javax.swing.JLabel txtDC;
	private javax.swing.JLabel txtGioiTinh;
	private javax.swing.JLabel txtMaHd;
	private javax.swing.JLabel txtNgayLap;
	private javax.swing.JLabel txtTenNV;
	private javax.swing.JLabel txtTenkh;
	private javax.swing.JLabel txtTienBangChu;
	private javax.swing.JLabel txtTongHD;
	private javax.swing.JLabel txtTongTien;
	private javax.swing.JLabel txtTongVAT;
	// End of variables declaration

}
