/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import controller.HoaDonRightClickPopUp;
import dao.DAO_Thuoc;
import entity.HoaDonBan;

/**
 *
 * @author HoangPC
 */
public class QuanLyHoaDonPanel extends javax.swing.JPanel implements KeyListener, ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DefaultTableModel md;
	private DAO_Thuoc daoBanthuoc = new DAO_Thuoc();
	private List<HoaDonBan> listHdBan;
	private HoaDonRightClickPopUp popUp;
	private List<HoaDonBan> listHDB = new ArrayList<HoaDonBan>();;

	/**
	 * Creates new form pnHoaDon
	 */
	public QuanLyHoaDonPanel() {
		initComponents();
		docDataHdBanVaoTable();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pnHeader = new javax.swing.JPanel();
		lblTitle = new javax.swing.JLabel();
		pnBody = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		lblMaHD = new javax.swing.JLabel();
		txtMaHD = new javax.swing.JTextField();
		lblTen = new javax.swing.JLabel();
		txtTenKH = new javax.swing.JTextField();
		txtSDTKH = new javax.swing.JTextField();
		lblSDT = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		txtSdtNV = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		btnXoaTrang = new javax.swing.JButton();
		btnChiTiet = new javax.swing.JButton();
		txtSlHD = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblHB = new javax.swing.JTable();
		btnSkipPrevius = new javax.swing.JButton();
		btnNextPrevius = new javax.swing.JButton();
		txtSoTrang = new javax.swing.JLabel();
		btnNextForward = new javax.swing.JButton();
		btnSkipForward = new javax.swing.JButton();

		pnHeader.setBackground(new java.awt.Color(1, 128, 145));

		lblTitle.setBackground(new java.awt.Color(255, 255, 255));
		lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		lblTitle.setForeground(new java.awt.Color(255, 255, 255));
		lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitle.setText("Quản lý hóa đơn");

		javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
		pnHeader.setLayout(pnHeaderLayout);
		pnHeaderLayout.setHorizontalGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnHeaderLayout.createSequentialGroup().addComponent(lblTitle,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(0, 0, 0)));
		pnHeaderLayout.setVerticalGroup(
				pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblTitle,
						javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE));

		pnBody.setBackground(new java.awt.Color(255, 255, 255));

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		lblMaHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		lblMaHD.setText("Mã HĐ:");

		txtMaHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		lblTen.setText("Tên KH:");

		txtTenKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtTenKH.setPreferredSize(new java.awt.Dimension(7, 30));

		txtSDTKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		lblSDT.setText("SĐT KH:");

		jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabel6.setText("Hiện có:");

		jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabel7.setText("hóa đơn");

		txtSdtNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel8.setText("SĐT NV:");

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		btnXoaTrang.setBackground(new java.awt.Color(204, 204, 204));
		btnXoaTrang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh (1).png"))); // NOI18N
		btnXoaTrang.setText("Làm mới");
		btnXoaTrang.setToolTipText("Làm mới mục");
		btnXoaTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		btnChiTiet.setBackground(new java.awt.Color(204, 204, 204));
		btnChiTiet.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		btnChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list.png"))); // NOI18N
		btnChiTiet.setText("Chi tiết");
		btnChiTiet.setToolTipText("Xem chi tiết hóa đơn");
		btnChiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnChiTietMousePressed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel3Layout.createSequentialGroup().addGap(0, 318, Short.MAX_VALUE)
								.addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
						javax.swing.GroupLayout.PREFERRED_SIZE));

		txtSlHD.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
		txtSlHD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		txtSlHD.setText("0");

		jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(29, 53, 87));
		jLabel1.setText("Quản lý hóa đơn");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator1)
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblMaHD, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel6)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtSlHD, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 526,
												Short.MAX_VALUE)
										.addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(txtSdtNV).addComponent(txtSDTKH)))))
						.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(0, 0,
								Short.MAX_VALUE)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(6, 6, 6).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtSDTKH, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(lblMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblTen, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(txtSdtNV, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
										.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtSlHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		
		tblHB.setFont(new java.awt.Font("Arial", 0, 16));
		tblHB.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã hóa đơn", "Ngày lập", "Mã khách hàng", "Tên khách hàng", "Nhân viên lập",
				"Tổng tiền" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tblHB.setGridColor(new java.awt.Color(204, 204, 204));
		tblHB.setRowHeight(34);
		tblHB.setSelectionBackground(new java.awt.Color(1, 128, 145));
		tblHB.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(tblHB);
		if (tblHB.getColumnModel().getColumnCount() > 0) {
			tblHB.getColumnModel().getColumn(0).setResizable(false);
			tblHB.getColumnModel().getColumn(0).setPreferredWidth(7);
			tblHB.getColumnModel().getColumn(1).setResizable(false);
			tblHB.getColumnModel().getColumn(2).setResizable(false);
			tblHB.getColumnModel().getColumn(2).setPreferredWidth(20);
			tblHB.getColumnModel().getColumn(3).setResizable(false);
			tblHB.getColumnModel().getColumn(4).setResizable(false);
			tblHB.getColumnModel().getColumn(5).setResizable(false);
		}

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
						.createSequentialGroup().addContainerGap().addComponent(jScrollPane1).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, 0)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
						.addGap(0, 0, 0)));

		btnSkipPrevius.setBackground(new java.awt.Color(204, 204, 204));
		btnSkipPrevius.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/img/baseline_skip_previous_white_24dp.png"))); // NOI18N
		btnSkipPrevius.setToolTipText("Trang đầu");
		btnSkipPrevius.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnSkipPrevius.setPreferredSize(new java.awt.Dimension(40, 30));

		btnNextPrevius.setBackground(new java.awt.Color(204, 204, 204));
		btnNextPrevius
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baseline_fast_rewind_white_24dp.png"))); // NOI18N
		btnNextPrevius.setToolTipText("Trang trước");
		btnNextPrevius.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnNextPrevius.setPreferredSize(new java.awt.Dimension(40, 30));

		txtSoTrang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		txtSoTrang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		txtSoTrang.setText("0");

		btnNextForward.setBackground(new java.awt.Color(204, 204, 204));
		btnNextForward.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/img/baseline_fast_forward_white_24dp.png"))); // NOI18N
		btnNextForward.setToolTipText("Trang sau");
		btnNextForward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnNextForward.setPreferredSize(new java.awt.Dimension(40, 30));

		btnSkipForward.setBackground(new java.awt.Color(204, 204, 204));
		btnSkipForward
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baseline_skip_next_white_24dp.png"))); // NOI18N
		btnSkipForward.setToolTipText("Trang cuối");
		btnSkipForward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnSkipForward.setPreferredSize(new java.awt.Dimension(40, 30));

		javax.swing.GroupLayout pnBodyLayout = new javax.swing.GroupLayout(pnBody);
		pnBody.setLayout(pnBodyLayout);
		pnBodyLayout.setHorizontalGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(pnBodyLayout.createSequentialGroup().addContainerGap()
						.addComponent(btnSkipPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnNextPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnNextForward, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnSkipForward, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		pnBodyLayout.setVerticalGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnBodyLayout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnNextForward, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnNextPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSkipPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSkipForward, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(pnBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0).addComponent(pnBody, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		// ------------
		md = (DefaultTableModel) tblHB.getModel();
		tblHB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				tblHDMouseReleased(evt);
			}
		});
		// ------------
		txtMaHD.addKeyListener(this);
		txtSDTKH.addKeyListener(this);
		txtSdtNV.addKeyListener(this);
		txtTenKH.addKeyListener(this);

		btnNextForward.addActionListener(this);
		btnSkipForward.addActionListener(this);
		btnNextPrevius.addActionListener(this);
		btnSkipPrevius.addActionListener(this);
	}// </editor-fold>//GEN-END:initComponents

	private void tblHDMouseReleased(MouseEvent evt) {
		popUp = new HoaDonRightClickPopUp(this);
		if (SwingUtilities.isRightMouseButton(evt)) {
			int r = tblHB.rowAtPoint(evt.getPoint());
			if (r >= 0 && r < tblHB.getRowCount()) {
				tblHB.setRowSelectionInterval(r, r);
			} else {
				tblHB.clearSelection();
			}
			int rowselect = tblHB.getSelectedRow();
			if (rowselect < 0)
				return;
			else {
				popUp.show(evt.getComponent(), evt.getX(), evt.getY());
			}

		}
	}

	private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimActionPerformed
		timTheoGoiy();
	}// GEN-LAST:event_btnTimActionPerformed

	private void btnChiTietMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnChiTietMousePressed
		xemChiTiet();
	}// GEN-LAST:event_btnChiTietMousePressed

	public void xemChiTiet() {
		int row = tblHB.getSelectedRow();
		if (row < 0) {
			JOptionPane.showMessageDialog(null, "Mời chọn hóa đơn cần xem chi tiết");
			return;
		}
		new ChitietHoadonBanJframe(tblHB.getValueAt(row, 0).toString()).setVisible(true);

	}

	private void docDataHdBanVaoTable() {
		listHDB = daoBanthuoc.getAllHdban();
		countDS = listHDB.size();
		md.getDataVector().removeAllElements();
		if (listHDB.size() == 0) {
			return;
		}
		for (int i = (trang - 1) * 20; i < trang * 20; i++) {
			try {
				HoaDonBan t = listHDB.get(i);
				md.addRow(new Object[] { t.getMaHoaDonBan(), t.getNgayLapHDBan(), t.getKh().getMaKhachHang(),
						t.getKh().getTenKhachHang(), t.getNv().getTenNV(),
						Math.round(Double.parseDouble(daoBanthuoc.tongGiaHoaDon(t.getMaHoaDonBan()))) });
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		txtSoTrang.setText(String.valueOf(trang));
		txtSlHD.setText("" + countDS);
		tblHB.clearSelection();
	}
//
	private void timTheoGoiy() {
		listHdBan = daoBanthuoc.getAllHdbanByHint(txtMaHD.getText(), txtSDTKH.getText(), txtTenKH.getText(),
				txtSdtNV.getText());
		md.getDataVector().removeAllElements();
		md.fireTableDataChanged();
		countDS = listHdBan.size();
		if (countDS == 0) {
//			txtSlHD.setText("" + 0);
			txtSoTrang.setText("1");
			return;
		}
//		int count = 0;
		for (int i = (trang - 1) * 20; i < trang * 20; i++) {
			try {
				HoaDonBan t = listHDB.get(i);
				md.addRow(new Object[] { t.getMaHoaDonBan(), t.getNgayLapHDBan(), t.getKh().getMaKhachHang(),
						t.getKh().getTenKhachHang(), t.getNv().getTenNV(),
						Math.round(Double.parseDouble(daoBanthuoc.tongGiaHoaDon(t.getMaHoaDonBan()))) });
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
//		txtSlHD.setText("" + soHD);
		tblHB.clearSelection();
	}

	// --------------------key--------------------------

	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void keyReleased(KeyEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if (o.equals(txtMaHD) || o.equals(txtSDTKH) || o.equals(txtSdtNV) || o.equals(txtTenKH)) {
			timTheoGoiy();
		}
	}

	@Override
	public void keyTyped(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnChiTiet;
	private javax.swing.JButton btnNextForward;
	private javax.swing.JButton btnNextPrevius;
	private javax.swing.JButton btnSkipForward;
	private javax.swing.JButton btnSkipPrevius;
	private javax.swing.JButton btnXoaTrang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JLabel lblMaHD;
	private javax.swing.JLabel lblSDT;
	private javax.swing.JLabel lblTen;
	private javax.swing.JLabel lblTitle;
	private javax.swing.JPanel pnBody;
	private javax.swing.JPanel pnHeader;
	private javax.swing.JTable tblHB;
	private javax.swing.JTextField txtMaHD;
	private javax.swing.JTextField txtSDTKH;
	private javax.swing.JTextField txtSdtNV;
	private javax.swing.JLabel txtSlHD;
	private javax.swing.JLabel txtSoTrang;
	private javax.swing.JTextField txtTenKH;

	private int trang = 1;
	private float flag;
	private int countDS;
//	private int soHD;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object obj = e.getSource();
		if (obj.equals(btnSkipPrevius)) {
			if (trang > 1) {
				trang = 1;
				docDataHdBanVaoTable();
			}
		}
		if (obj.equals(btnNextPrevius)) {
			if (trang > 1) {
				trang -= 1;
				docDataHdBanVaoTable();
			}
		}
		if (obj.equals(btnNextForward)) {
			flag = (float) countDS / 20;
			if (trang < (int) Math.ceil(flag)) {
				trang += 1;
				docDataHdBanVaoTable();
			}
		}
		if (obj.equals(btnSkipForward)) {
			flag = (float) countDS / 20;
			if (trang < (int) Math.ceil(flag)) {
				trang = (int) Math.ceil(flag);
				docDataHdBanVaoTable();
			}
		}
	}

}
