/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import controller.ClassGetImg;
import dao.DAO_CongDung;
import dao.DAO_Thuoc;
import entity.CongDung;
import entity.Thuoc;

/**
 *
 * @author HoangPC
 */
public class SuaThongTinThuocJPanel extends javax.swing.JFrame implements ActionListener, MouseListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DAO_Thuoc daoThuoc;
	private DAO_CongDung dao_CongDung;
	private QuanLyThuocJPanel quanLyThuocJPanel;
	private String maThuoc;
	private String fileIn;

	public SuaThongTinThuocJPanel(String maThuoc, QuanLyThuocJPanel quanLyThuocJPanel) {
		initComponents();
		daoThuoc = new DAO_Thuoc();
		dao_CongDung = new DAO_CongDung();
		fileIn = "";
		setLocationRelativeTo(null);
		this.quanLyThuocJPanel = quanLyThuocJPanel;
		this.maThuoc = maThuoc;
		docThongTinThuocLenFrame(maThuoc);
	}

	private boolean kiemTraThongTin() {
		if (txtGiaBan.getText().equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(this, "Mời nhập giá bán!", "Thông báo", JOptionPane.WARNING_MESSAGE);
			txtGiaBan.requestFocus();
			return false;
		} else if (txtTenThuoc.getText().equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(this, "Mời nhập tên thuốc", "Thông báo", JOptionPane.WARNING_MESSAGE);
			txtTenThuoc.requestFocus();
			return false;
		}

		return true;

	}

	public SuaThongTinThuocJPanel() {
		initComponents();
		setLocationRelativeTo(null);

	}

	private void docThongTinThuocLenFrame(String maThuoc) {
		Thuoc t = daoThuoc.timThuocTheoMa(maThuoc);

		new Thread(() -> {
			List<String> listItemp = new ArrayList<>();
			listItemp = daoThuoc.getDVT();
			for (String Itemp : listItemp) {
				jcbDVT.addItem(Itemp);
			}
			jcbDVT.setSelectedItem(t.getDonViTinh());
		}).start();
		new Thread(() -> {
			List<String> listItemp1 = new ArrayList<>();
			listItemp1 = new ArrayList<>(dao_CongDung.getAllNhomCongDung());
			for (String Itemp : listItemp1) {
				jcbNhomCongDung.addItem(Itemp);
			}
			jcbNhomCongDung.setSelectedItem(t.getCongDung().getNhomCongDung());
			jcbCongDung.setSelectedItem(t.getCongDung().getCongDung());
		}).start();
		txtTrangThai.setText(t.isTrangThaiKD() == true ? "Đang kinh doanh" : "Ngừng kinh doanh");
		txtTenThuoc.setText(t.getTenThuoc());
		txtQuyCachDongGoi.setText(t.getQuyCachDongGoi());
		txtHoatChat.setText(t.getThanhPhan());
		txtVat.setText(String.valueOf(t.getThueVAT()));
		txtDangBaoChe.setText(t.getDangBaoChe());
		txtNongDo.setText(t.getHamLuong());
		txtSoDangKy.setText(t.getSoDK());
		txtHangSX.setText(t.getcTySanXuat());
		txtNuocSX.setText(t.getNuocSanXuat());
		txtGiaBan.setText(String.valueOf(t.getGiaBan()));
		ClassGetImg imgClass = new ClassGetImg();
		imgClass.setImgChiTiet(lblHinh, "src/main/java/thuocImg/" + maThuoc);
	}

	private void lamMoi(String maThuoc) {
		Thuoc t = daoThuoc.timThuocTheoMa(maThuoc);
		txtTrangThai.setText(t.isTrangThaiKD() == true ? "Đang kinh doanh" : "Ngừng kinh doanh");
		txtTenThuoc.setText(t.getTenThuoc());
		txtQuyCachDongGoi.setText(t.getQuyCachDongGoi());
		txtHoatChat.setText(t.getThanhPhan());
		txtVat.setText(String.valueOf(t.getThueVAT()));
		txtDangBaoChe.setText(t.getDangBaoChe());
		txtNongDo.setText(t.getHamLuong());
		txtSoDangKy.setText(t.getSoDK());
		txtHangSX.setText(t.getcTySanXuat());
		txtNuocSX.setText(t.getNuocSanXuat());
		txtGiaBan.setText(String.valueOf(t.getGiaBan()));
		jcbDVT.setSelectedItem(t.getDonViTinh());
		jcbNhomCongDung.setSelectedItem(t.getCongDung().getNhomCongDung());
		jcbCongDung.setSelectedItem(t.getCongDung().getCongDung());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		txtTrangThai = new javax.swing.JTextField();
		lblQCDG2 = new javax.swing.JLabel();
		lblQCDG7 = new javax.swing.JLabel();
		lblQCDG8 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		lblQCDG3 = new javax.swing.JLabel();
		txtTenThuoc = new javax.swing.JTextField();
		jSeparator3 = new javax.swing.JSeparator();
		lblQCDG10 = new javax.swing.JLabel();
		jcbNhomCongDung = new javax.swing.JComboBox<>();
		jcbCongDung = new javax.swing.JComboBox<>();
		lblQCDG11 = new javax.swing.JLabel();
		jSeparator4 = new javax.swing.JSeparator();
		jPanel4 = new javax.swing.JPanel();
		lblMaThuoc = new javax.swing.JLabel();
		txtSoDangKy = new javax.swing.JTextField();
		lblTenHC = new javax.swing.JLabel();
		txtHoatChat = new javax.swing.JTextField();
		lblQCDG6 = new javax.swing.JLabel();
		txtNongDo = new javax.swing.JTextField();
		lblQCDG = new javax.swing.JLabel();
		txtQuyCachDongGoi = new javax.swing.JTextField();
		lblQCDG4 = new javax.swing.JLabel();
		txtHangSX = new javax.swing.JTextField();
		lblQCDG5 = new javax.swing.JLabel();
		txtNuocSX = new javax.swing.JTextField();
		txtGiaBan = new javax.swing.JTextField();
		txtVat = new javax.swing.JTextField();
		txtDangBaoChe = new javax.swing.JTextField();
		btnHuy = new javax.swing.JButton();
		btnXacNhan = new javax.swing.JButton();
		btnLamMoi = new javax.swing.JButton();
		lblQCDG12 = new javax.swing.JLabel();
		jcbDVT = new javax.swing.JComboBox<>();
		jPanel5 = new javax.swing.JPanel();
		lblHinh = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Sửa thông tin thuốc");
		setResizable(false);

		jPanel2.setBackground(new java.awt.Color(1, 128, 145));

		jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Sửa thông tin thuốc");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		txtTrangThai.setEditable(false);
		txtTrangThai.setBackground(new java.awt.Color(255, 255, 255));
		txtTrangThai.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
		txtTrangThai.setForeground(new java.awt.Color(255, 0, 0));
		txtTrangThai.setText("Đang kinh doanh");
		txtTrangThai.setBorder(null);

		lblQCDG2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG2.setText("Dạng bào chế:");

		lblQCDG7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG7.setText("VAT(%):");

		lblQCDG8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG8.setText("Giá bán:");
		lblQCDG8.setMaximumSize(new java.awt.Dimension(101, 17));
		lblQCDG8.setMinimumSize(new java.awt.Dimension(101, 17));
		lblQCDG8.setPreferredSize(new java.awt.Dimension(101, 17));

		lblQCDG3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG3.setText("Tên thuốc:");
		lblQCDG3.setMaximumSize(new java.awt.Dimension(101, 17));
		lblQCDG3.setMinimumSize(new java.awt.Dimension(101, 17));
		lblQCDG3.setPreferredSize(new java.awt.Dimension(101, 17));

		txtTenThuoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblQCDG10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG10.setText("Nhóm:");

		jcbNhomCongDung.setBackground(new java.awt.Color(153, 153, 153));
		jcbNhomCongDung.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

		jcbCongDung.setBackground(new java.awt.Color(153, 153, 153));
		jcbCongDung.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

		lblQCDG11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG11.setText("Công dụng:");

		jPanel4.setBackground(new java.awt.Color(245, 245, 245));
		jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

		lblMaThuoc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblMaThuoc.setText("Số đăng ký:");
		lblMaThuoc.setMaximumSize(new java.awt.Dimension(101, 17));
		lblMaThuoc.setMinimumSize(new java.awt.Dimension(101, 17));
		lblMaThuoc.setPreferredSize(new java.awt.Dimension(101, 17));

		txtSoDangKy.setEditable(false);
		txtSoDangKy.setBackground(new java.awt.Color(245, 245, 245));
		txtSoDangKy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtSoDangKy.setFocusable(false);

		lblTenHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblTenHC.setText("Hoạt chất:");
		lblTenHC.setMaximumSize(new java.awt.Dimension(101, 17));
		lblTenHC.setMinimumSize(new java.awt.Dimension(101, 17));
		lblTenHC.setPreferredSize(new java.awt.Dimension(101, 17));

		txtHoatChat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblQCDG6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG6.setText("Hàm lượng:");
		lblQCDG6.setMaximumSize(new java.awt.Dimension(101, 17));
		lblQCDG6.setMinimumSize(new java.awt.Dimension(101, 17));
		lblQCDG6.setPreferredSize(new java.awt.Dimension(101, 17));

		txtNongDo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblQCDG.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG.setText("QC đóng gói:");
		lblQCDG.setMaximumSize(new java.awt.Dimension(101, 17));
		lblQCDG.setMinimumSize(new java.awt.Dimension(101, 17));
		lblQCDG.setPreferredSize(new java.awt.Dimension(101, 17));

		txtQuyCachDongGoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblQCDG4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG4.setText("Hãng sản xuất:");
		lblQCDG4.setMaximumSize(new java.awt.Dimension(101, 17));
		lblQCDG4.setMinimumSize(new java.awt.Dimension(101, 17));
		lblQCDG4.setPreferredSize(new java.awt.Dimension(101, 17));

		txtHangSX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		lblQCDG5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG5.setText("Nước sản xuất:");
		lblQCDG5.setMaximumSize(new java.awt.Dimension(101, 17));
		lblQCDG5.setMinimumSize(new java.awt.Dimension(101, 17));
		lblQCDG5.setPreferredSize(new java.awt.Dimension(101, 17));

		txtNuocSX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
								.addComponent(lblMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(txtSoDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout.createSequentialGroup()
										.addComponent(lblTenHC, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(txtHoatChat))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(lblQCDG6, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(txtNongDo))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(lblQCDG, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(txtQuyCachDongGoi))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(lblQCDG4, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(txtHangSX))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(lblQCDG5, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(txtNuocSX)))
						.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel4Layout.createSequentialGroup().addGap(1, 1, 1).addComponent(txtSoDangKy,
								javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTenHC, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtHoatChat, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblQCDG6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtNongDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblQCDG, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtQuyCachDongGoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblQCDG4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblQCDG5, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtNuocSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		txtGiaBan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		txtVat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		txtDangBaoChe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		btnHuy.setBackground(new java.awt.Color(204, 204, 204));
		btnHuy.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forbidden.png"))); // NOI18N
		btnHuy.setText("Hủy");
		btnHuy.setToolTipText("Hủy thêm nhân viên");

		btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
		btnXacNhan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick .png"))); // NOI18N
		btnXacNhan.setText("Xác nhận");
		btnXacNhan.setToolTipText("Thêm nhân viên");

		btnLamMoi.setBackground(new java.awt.Color(204, 204, 204));
		btnLamMoi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh (1).png"))); // NOI18N
		btnLamMoi.setText("Làm mới");
		btnLamMoi.setToolTipText("Làm mới mục thêm");

		lblQCDG12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblQCDG12.setText("ĐVT:");

		jcbDVT.setBackground(new java.awt.Color(153, 153, 153));
		jcbDVT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));
		jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-image.png"))); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblHinh,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jSeparator3).addComponent(jSeparator2).addComponent(jSeparator1)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout
										.createSequentialGroup()
										.addComponent(lblQCDG8, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtGiaBan)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lblQCDG7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtVat).addGap(18, 18, 18).addComponent(lblQCDG12)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jcbDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblQCDG2)
												.addComponent(lblQCDG10, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel3Layout.createSequentialGroup()
																.addComponent(jcbNhomCongDung, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGap(18, 18, 18).addComponent(lblQCDG11)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jcbCongDung, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.addComponent(txtDangBaoChe)))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(lblQCDG3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtTenThuoc).addGap(18, 18, 18).addComponent(txtTrangThai,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										jPanel3Layout.createSequentialGroup()
												.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(20, 20, 20)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addGap(8, 8, 8)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtTenThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
								.addComponent(lblQCDG3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(txtTrangThai))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(lblQCDG7, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(txtVat, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblQCDG8, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jcbDVT, javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblQCDG12,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtDangBaoChe, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblQCDG2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblQCDG10, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jcbNhomCongDung)
								.addComponent(lblQCDG11, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jcbCongDung, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		pack();
		jcbNhomCongDung.addActionListener(this);
		btnHuy.addActionListener(this);
		btnXacNhan.addActionListener(this);
		btnLamMoi.addActionListener(this);
		lblHinh.addMouseListener(this);
	}// </editor-fold>//GEN-END:initComponents

	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getSource().equals(btnHuy)) {
			int c = JOptionPane.showConfirmDialog(null, "Xác nhận hủy?", "Thông báo", JOptionPane.YES_NO_OPTION);
			if (c == JOptionPane.YES_OPTION)
				dispose();
		} else if (e.getSource().equals(jcbNhomCongDung)) {
			if (jcbNhomCongDung.getItemCount() > 1) {
				Vector<String> congdungVT = dao_CongDung.getAllCongDung(jcbNhomCongDung.getSelectedItem().toString());
				congdungVT.removeElementAt(0);
				jcbCongDung.setModel(new DefaultComboBoxModel<String>(congdungVT));
				jcbCongDung.setSelectedIndex(0);
			}
		} else if (e.getSource().equals(btnXacNhan)) {
			String ten = txtTenThuoc.getText().trim();
			double giaBan = Double.parseDouble(txtGiaBan.getText().trim());
 			String donViTinh = jcbDVT.getSelectedItem().toString();
			String hoatChat = txtHoatChat.getText().trim();
			String quyCachDongGoi = txtQuyCachDongGoi.getText().trim();
			String dangBaoChe = txtDangBaoChe.getText().trim();
			String hamLuong = txtNongDo.getText().trim();
			String cTySanXuat = txtHangSX.getText().trim();
			String nuocSanXuat = txtNuocSX.getText().trim();
			boolean trangThaiKD = txtTrangThai.getText().trim() == "Đang kinh doanh" ? true : false;
			float vat = Float.parseFloat(txtVat.getText().trim());
			String soDK = txtSoDangKy.getText().trim();
			String maCongDung = dao_CongDung.getMaCongDungTheoLoaiVaCongDung(
					jcbNhomCongDung.getSelectedItem().toString(), jcbCongDung.getSelectedItem().toString());
			CongDung congDung = dao_CongDung.getCongDungByMaCongDung(maCongDung);
			if (kiemTraThongTin() == true) {
				Thuoc t = new Thuoc(maThuoc, ten, giaBan, donViTinh, hoatChat, quyCachDongGoi, dangBaoChe, hamLuong,
						cTySanXuat, nuocSanXuat, trangThaiKD, vat, soDK, congDung);

				int n = JOptionPane.showConfirmDialog(null,
						"<html>Bạn có muốn cập nhật thông tin thuốc <b>'" + txtTenThuoc.getText().trim() + "'</b> không?</html>", "",
						JOptionPane.YES_NO_OPTION);

				if (n == JOptionPane.YES_OPTION) {
					if (daoThuoc.suaThuoc(t) == true) {
						quanLyThuocJPanel.dataToTBSP();
						JOptionPane.showMessageDialog(null, "<html>Thuốc <b>'" + t.getTenThuoc() + "'</b> đã được cập nhật</html>");
						dispose();
						ClassGetImg imgc = new ClassGetImg();
						try {
							imgc.createDropImgThuoc("src/main/java/thuocImg/"+t.getMaThuoc(), fileIn);
						} catch (IOException e1) {
							JOptionPane.showMessageDialog(null, "Lưu hình thất bại");
							e1.printStackTrace();
						}
						return;
					}
					JOptionPane.showMessageDialog(null, "Cập nhật thuốc " + t.getTenThuoc() + " thất bại");
				}

			}
		} else if (e.getSource().equals(btnLamMoi)) {
			lamMoi(maThuoc);
		}
	}
	
	//----------------mouse----------------
	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		if(e.getSource().equals(lblHinh)) {
			ClassGetImg imgc = new ClassGetImg();
			try {
				fileIn = imgc.setImg("src/main/java/thuocImg/", lblHinh);
			} catch (IOException e1) {
				e1.printStackTrace();
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChiTietThuocJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChiTietThuocJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChiTietThuocJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChiTietThuocJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChiTietThuocJframe().setVisible(true);
			}

		});

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnHuy;
	private javax.swing.JButton btnLamMoi;
	private javax.swing.JButton btnXacNhan;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JComboBox<String> jcbCongDung;
	private javax.swing.JComboBox<String> jcbDVT;
	private javax.swing.JComboBox<String> jcbNhomCongDung;
	private javax.swing.JLabel lblHinh;
	private javax.swing.JLabel lblMaThuoc;
	private javax.swing.JLabel lblQCDG;
	private javax.swing.JLabel lblQCDG10;
	private javax.swing.JLabel lblQCDG11;
	private javax.swing.JLabel lblQCDG12;
	private javax.swing.JLabel lblQCDG2;
	private javax.swing.JLabel lblQCDG3;
	private javax.swing.JLabel lblQCDG4;
	private javax.swing.JLabel lblQCDG5;
	private javax.swing.JLabel lblQCDG6;
	private javax.swing.JLabel lblQCDG7;
	private javax.swing.JLabel lblQCDG8;
	private javax.swing.JLabel lblTenHC;
	private javax.swing.JTextField txtDangBaoChe;
	private javax.swing.JTextField txtGiaBan;
	private javax.swing.JTextField txtHangSX;
	private javax.swing.JTextField txtHoatChat;
	private javax.swing.JTextField txtNongDo;
	private javax.swing.JTextField txtNuocSX;
	private javax.swing.JTextField txtQuyCachDongGoi;
	private javax.swing.JTextField txtSoDangKy;
	private javax.swing.JTextField txtTenThuoc;
	private javax.swing.JTextField txtTrangThai;
	private javax.swing.JTextField txtVat;

	
}
