/*
d * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import dao.DAO_DiaChi;
import dao.DAO_KhachHang;
import entity.DiaChi;
import entity.KhachHang;

/**
 *
 * @author HoangPC
 */
public class ThemKhachHangJframe extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	DAO_DiaChi DAODiaChi= new DAO_DiaChi();
	DAO_KhachHang daoKhachHang= new DAO_KhachHang();
   private QuanLyKhachHangPanel khpn;
   private boolean trangThai;
private Vector<String> vecTinhTP= new Vector<String>();
   
    
    public ThemKhachHangJframe(QuanLyKhachHangPanel khpn, boolean trangThai) {
        initComponents();
        setLocationRelativeTo(null);
        this.khpn = khpn;
        this.trangThai = trangThai;
        txtMa.setText(daoKhachHang.taoMaNgauNhienKH());
    }
    
    public ThemKhachHangJframe() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblDC = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblMa1 = new javax.swing.JLabel();
        jcbGioiTinh = new javax.swing.JComboBox<>();
        lblSDT1 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        jcbTinh = new javax.swing.JComboBox<>();
        jcbQuan = new javax.swing.JComboBox<>();
        jcbXa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm khách hàng");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 53, 87));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm khách hàng mới");

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("NHÀ THUỐC DRAMACITY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblMa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMa.setText("Mã khách hàng:");

        txtMa.setEditable(false);
        txtMa.setBackground(new java.awt.Color(255, 255, 255));
        txtMa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMa.setBorder(null);
        txtMa.setFocusable(false);

        lblTen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTen.setText("Tên khách hàng:");

        txtTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblDC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDC.setText("Địa chỉ:");

        btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
        btnXacNhan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick .png"))); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setToolTipText("Thêm nhân viên");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXacNhanMousePressed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forbidden.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setToolTipText("Hủy thêm nhân viên");

        lblMa1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMa1.setText("Giới tính:");

        jcbGioiTinh.setBackground(new java.awt.Color(153, 153, 153));
        jcbGioiTinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        lblSDT1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSDT1.setText("Số điện thoại:");
        lblSDT1.setToolTipText("");

        txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSDT.setToolTipText("");

        btnLamMoi.setBackground(new java.awt.Color(204, 204, 204));
        btnLamMoi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setToolTipText("Làm mới mục thêm");

        jcbTinh.setBackground(new java.awt.Color(153, 153, 153));
        jcbTinh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tỉnh/TP" }));

        jcbQuan.setBackground(new java.awt.Color(153, 153, 153));
        jcbQuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quận/Huyện" }));

        jcbXa.setBackground(new java.awt.Color(153, 153, 153));
        jcbXa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbXa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phường/Xã" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSDT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTen)
                    .addComponent(txtSDT)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbQuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbXa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbXa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMa)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        //----------------
        loadTinh();
        
        jcbTinh.addActionListener(new ActionListener() {
			
			private Vector<String> vecQuanHuyen;
			private Vector<String> vecPhuongXa;

			@Override
			public void actionPerformed(ActionEvent e) {
				if(jcbTinh.getSelectedItem().toString().equalsIgnoreCase("Tỉnh/Thành phố")) {
					vecQuanHuyen = new Vector<String>();
					vecQuanHuyen.add("Quận/Huyện");
					DefaultComboBoxModel<String> mdQuan = new DefaultComboBoxModel<>(vecQuanHuyen);
					jcbQuan.setModel(mdQuan);
					vecPhuongXa = new Vector<String>();
					vecPhuongXa.add("Phường/Xã");
					DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
					jcbXa.setModel(mdPhuong);
					return;
				}
				vecQuanHuyen = DAODiaChi.getAllHuyenTheoTinh(jcbTinh.getSelectedItem().toString());
				DefaultComboBoxModel<String> mdQuanHuyen = new DefaultComboBoxModel<>(vecQuanHuyen);
				jcbQuan.setModel(mdQuanHuyen);
			}
		});
        jcbQuan.addActionListener(new ActionListener() {
			
			private Vector<String> vecPhuongXa;

			@Override
			public void actionPerformed(ActionEvent e) {
				if(jcbQuan.getSelectedItem().toString().equalsIgnoreCase("Quận/Huyện")) {
					vecPhuongXa = new Vector<String>();
					vecPhuongXa.add("Phường/Xã");
					DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
					jcbXa.setModel(mdPhuong);
					return;
				}
				vecPhuongXa = DAODiaChi.getAllPhuongXaTheoTinhVaHuyen(jcbTinh.getSelectedItem().toString(), jcbQuan.getSelectedItem().toString());
				DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
				jcbXa.setModel(mdPhuong);
			}
		});
        btnLamMoi.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				lammoi();
			}
		});
        btnHuy.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
        
    }// </editor-fold>//GEN-END:initComponents

    private void lammoi() {
        txtMa.setText(daoKhachHang.taoMaNgauNhienKH());
    	txtTen.setText("");
		txtSDT.setText("");
		jcbTinh.setSelectedIndex(0);
		jcbQuan.setSelectedIndex(0);
		jcbXa.setSelectedIndex(0);
		txtTen.requestFocus();
    }
    
    private void btnXacNhanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMousePressed
        
        if(trangThai){
        	if(themKH()) {
        		khpn.chuyenTuKhachHangDenBanThuocBangThem(txtTen.getText(), txtSDT.getText(), DAODiaChi.getMaDCTheoTinhHuyenXa(jcbTinh.getSelectedItem().toString(), jcbQuan.getSelectedItem().toString(), jcbXa.getSelectedItem().toString()));
                dispose();
                return;
        	}
        }
        if(themKH()) {
        	dispose();
        	int c = JOptionPane.showConfirmDialog(null, "Bạn có muốn tiếp tục thêm khách hàng mới ?");
        	if(c == JOptionPane.YES_OPTION) {
        		this.setVisible(true);
        		lammoi();
        	}
        }
    }
    

	private void loadTinh() {
		vecTinhTP = DAODiaChi.getAllTinh();
		if(vecTinhTP.size() == 1) {
			JOptionPane.showMessageDialog(null, "Lỗi khi đọc danh sách tỉnh!");
			return;
		}
		DefaultComboBoxModel<String> md = new DefaultComboBoxModel<String>(vecTinhTP);
		jcbTinh.setModel(md);
	}
    private boolean kiemTraThongTin() {
    	if(txtTen.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Tên không được bỏ trống!");
			txtTen.requestFocus();
			return false;
		}
		else if(txtSDT.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Số điện thoại không được bỏ trống!");
			txtSDT.requestFocus();
			return false;
		}
		else if(jcbXa.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(this, "Mời nhập địa chỉ khách hàng!");
			txtSDT.requestFocus();
			return false;
		}


		String ten= txtTen.getText();
		if (!ten.matches(
				"^([A-Za-z0-9ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴÝỶỸàáâãèéêìíòóôõùúăđĩũơưăạảấầẩẫậắằẳẵặẹẻẽềềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ]*\\s{0,1})+$")) {
			JOptionPane.showMessageDialog(this, "Tên không hợp lệ! (Phải bắt đầu bằng chữ hoa, không chứa số)");
			txtTen.selectAll();
			txtTen.requestFocus();
			return false;

		}
		String sdt = txtSDT.getText();
		if(!sdt.matches("(^(03)[2-9]\\d{7})|(^(07)[06-9]\\d{7})|(^(08)[1-5]\\d{7})|(^(056)\\d{7})|(^(058)\\d{7})|(^(059)\\d{7})|(^(09)[0-46-9]\\d{7})")) {
			JOptionPane.showMessageDialog(this, "Số điện thoại không có thực!");
			txtSDT.selectAll();
			txtSDT.requestFocus();
			return false;
		}
		
    	
    	return true;
    }

    private boolean themKH() {
    	if(!kiemTraThongTin())
    		return false;
    	String ma = txtMa.getText();
    	String ten = txtTen.getText();
    	String sdt = txtSDT.getText();
    	String tinhTP = jcbTinh.getSelectedItem().toString();
    	String huyen=jcbQuan.getSelectedItem().toString();
    	String xa= jcbXa.getSelectedItem().toString();

    	boolean gioiTinh = jcbGioiTinh.getSelectedItem().toString() == "Nam" ? true:false;
    	boolean trangThai = true;

    	KhachHang k= new KhachHang(ma, ten, gioiTinh, sdt, new DiaChi( DAODiaChi.getMaDCTheoTinhHuyenXa(tinhTP, huyen, xa)), trangThai);
    	if(daoKhachHang.themKH(k)) {
    		JOptionPane.showMessageDialog(this, "<html>Thêm thành công khách hàng <b>"+ ten +"</b></html>");
    		khpn.xoaKH();
    		dispose();
    	}
    	else {
    		JOptionPane.showMessageDialog(this, "Tài khoản này đã tồn tại!");
    		return false;
    	}
    	return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemKhachHangJframe().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbGioiTinh;
    private javax.swing.JComboBox<String> jcbQuan;
    private javax.swing.JComboBox<String> jcbTinh;
    private javax.swing.JComboBox<String> jcbXa;
    private javax.swing.JLabel lblDC;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMa1;
    private javax.swing.JLabel lblSDT1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

}
