/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import dao.DAO_DiaChi;
import dao.DAO_NhanVien;
import entity.DiaChi;
import entity.NhanVien;

/**
 *
 * @author HoangPC
 */
public class ThemNhanVienJframe extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private boolean flagPassShow = false;
	private DAO_NhanVien daoNV = new DAO_NhanVien();
	private JComboBox jcbTinh;
	private JComboBox jcbXa;
	private JLabel lblDC3;
	private Vector<String> vecTinhTP = new Vector<String>();
	private DAO_DiaChi daoDiaChi = new DAO_DiaChi();

	public ThemNhanVienJframe() {
		initComponents();
		setLocationRelativeTo(null);
		btnNhanVien.setSelected(true);
		loadTinh();
		txtMaNV.setText(daoNV.taoMaNgauNhienHDN());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		GroupLoai = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		lblTitle = new javax.swing.JLabel();
		lblMa = new javax.swing.JLabel();
		txtMaNV = new javax.swing.JTextField();
		lblTen = new javax.swing.JLabel();
		txtTenNV = new javax.swing.JTextField();
		LBLCMND = new javax.swing.JLabel();
		txtCMND = new javax.swing.JTextField();
		lblDC = new javax.swing.JLabel();
		btnXacNhan = new javax.swing.JButton();
		btnHuy = new javax.swing.JButton();
		lblDC1 = new javax.swing.JLabel();
		lblMa1 = new javax.swing.JLabel();
		jcbGioiTinh = new javax.swing.JComboBox<>();
		lblSDT1 = new javax.swing.JLabel();
		txtSDT = new javax.swing.JTextField();
		btnLamMoi = new javax.swing.JButton();
		btnHienPass = new javax.swing.JButton();
		txtMatKhau = new javax.swing.JPasswordField();
		lblDC3 = new javax.swing.JLabel();
		btnNhanVien = new javax.swing.JRadioButton();
		btnQuanLy = new javax.swing.JRadioButton();
		jcbTinh = new javax.swing.JComboBox<>();
		jcbQuan = new javax.swing.JComboBox<>();
		jcbXa = new javax.swing.JComboBox<>();

		GroupLoai.add(btnQuanLy);
		GroupLoai.add(btnNhanVien);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Thêm nhà cung cấp");
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(29, 53, 87));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Thêm nhân viên mới");

		lblTitle.setBackground(new java.awt.Color(255, 255, 255));
		lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitle.setText("NHÀ THUỐC DRAMACITY");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)));

		lblMa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblMa.setText("Mã nhân viên:");

		txtMaNV.setEditable(false);
		txtMaNV.setBackground(new java.awt.Color(255, 255, 255));
		txtMaNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtMaNV.setBorder(null);
		txtMaNV.setFocusable(false);

		lblTen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblTen.setText("Tên nhân viên:");

		txtTenNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		LBLCMND.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		LBLCMND.setText("CMND:");
		LBLCMND.setToolTipText("Chứng minh nhân dân");

		txtCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtCMND.setToolTipText("Chứng minh nhân dân");

		lblDC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblDC.setText("Địa chỉ:");

		btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
		btnXacNhan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick .png"))); // NOI18N
		btnXacNhan.setText("Xác nhận");
		btnXacNhan.setToolTipText("Thêm nhân viên");
		btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnXacNhanMousePressed(evt);
			}
		});

		btnHuy.setBackground(new java.awt.Color(204, 204, 204));
		btnHuy.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forbidden.png"))); // NOI18N
		btnHuy.setText("Hủy");
		btnHuy.setToolTipText("Hủy thêm nhân viên");
		btnHuy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuyActionPerformed(evt);
			}
		});

		lblDC1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblDC1.setText("Mật khẩu:");

		lblMa1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblMa1.setText("Giới tính:");

		jcbGioiTinh.setBackground(new java.awt.Color(153, 153, 153));
		jcbGioiTinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

		lblSDT1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblSDT1.setText("SĐT:");
		lblSDT1.setToolTipText("");

		txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtSDT.setToolTipText("");

		btnLamMoi.setBackground(new java.awt.Color(204, 204, 204));
		btnLamMoi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh (1).png"))); // NOI18N
		btnLamMoi.setText("Làm mới");
		btnLamMoi.setToolTipText("Làm mới mục thêm");
		btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnLamMoiMousePressed(evt);
			}
		});

		btnHienPass.setBackground(new java.awt.Color(204, 204, 204));
		btnHienPass
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baseline_visibility_black_24dp.png"))); // NOI18N
		btnHienPass.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHienPassActionPerformed(evt);
			}
		});

		txtMatKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		txtMatKhau.setText("123");

		lblDC3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		lblDC3.setText("Loại:");

		btnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
		btnNhanVien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		btnNhanVien.setText("Nhân Viên");

		btnQuanLy.setBackground(new java.awt.Color(255, 255, 255));
		btnQuanLy.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		btnQuanLy.setText("Quản Lý");

		jcbTinh.setBackground(new java.awt.Color(153, 153, 153));
		jcbTinh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jcbTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tỉnh/TP" }));

		jcbQuan.setBackground(new java.awt.Color(153, 153, 153));
		jcbQuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jcbQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quận/Huyện" }));

		jcbXa.setBackground(new java.awt.Color(153, 153, 153));
		jcbXa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jcbXa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phường/Xã" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(46, 46, 46).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblDC3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblDC1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblDC, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(LBLCMND, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
								.addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnNhanVien)
								.addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 268,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(txtMatKhau)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnHienPass, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(lblSDT1)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jcbTinh, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jcbQuan, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jcbXa, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(txtSDT)))
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(txtMaNV)
												.addGap(18, 18, 18).addComponent(lblMa1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 172,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(48, 48, 48)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(LBLCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jcbQuan, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblDC, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jcbTinh, javax.swing.GroupLayout.PREFERRED_SIZE,
																30, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jcbXa, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtMaNV)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE,
																30, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(lblSDT1, javax.swing.GroupLayout.PREFERRED_SIZE,
																30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMatKhau)
								.addComponent(btnHienPass, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
						.addGap(10, 10, 10)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblDC3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(50, 50, 50)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		// -------------------------------------------------------------
		jcbTinh.addActionListener(new ActionListener() {

			private Vector<String> vecQuanHuyen;
			private Vector<String> vecPhuongXa;

			@Override
			public void actionPerformed(ActionEvent e) {
				if (jcbTinh.getSelectedItem().toString().equalsIgnoreCase("Tỉnh/Thành phố")) {
					vecQuanHuyen = new Vector<String>();
					vecQuanHuyen.add("Quận/Huyện");
					DefaultComboBoxModel<String> mdQuan = new DefaultComboBoxModel<>(vecQuanHuyen);
					jcbQuan.setModel(mdQuan);
					vecPhuongXa = new Vector<String>();
					vecPhuongXa.add("Phường/Xã");
					DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
					jcbXa.setModel(mdPhuong);
					return;
				}
				vecQuanHuyen = daoDiaChi.getAllHuyenTheoTinh(jcbTinh.getSelectedItem().toString());
				DefaultComboBoxModel<String> mdQuanHuyen = new DefaultComboBoxModel<>(vecQuanHuyen);
				jcbQuan.setModel(mdQuanHuyen);
			}
		});
		jcbQuan.addActionListener(new ActionListener() {

			private Vector<String> vecPhuongXa;

			@Override
			public void actionPerformed(ActionEvent e) {
				if (jcbQuan.getSelectedItem().toString().equalsIgnoreCase("Quận/Huyện")) {
					vecPhuongXa = new Vector<String>();
					vecPhuongXa.add("Phường/Xã");
					DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
					jcbXa.setModel(mdPhuong);
					return;
				}
				vecPhuongXa = daoDiaChi.getAllPhuongXaTheoTinhVaHuyen(jcbTinh.getSelectedItem().toString(),
						jcbQuan.getSelectedItem().toString());
				DefaultComboBoxModel<String> mdPhuong = new DefaultComboBoxModel<>(vecPhuongXa);
				jcbXa.setModel(mdPhuong);
			}
		});

	}// </editor-fold>//GEN-END:initComponents

	private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	private void btnXacNhanMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnXacNhanMousePressed
		themNV();
	}

	private void btnLamMoiMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnLamMoiMousePressed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnLamMoiMousePressed

	private void btnHienPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHienPassActionPerformed
		if (flagPassShow == false) {
			flagPassShow = true;
			btnHienPass.setIcon(
					new javax.swing.ImageIcon(getClass().getResource("/img/baseline_visibility_off_black_24dp.png")));
			txtMatKhau.setEchoChar((char) 0);
		} else {
			flagPassShow = false;
			btnHienPass.setIcon(
					new javax.swing.ImageIcon(getClass().getResource("/img/baseline_visibility_black_24dp.png")));
			txtMatKhau.setEchoChar('*');
		}
	}// GEN-LAST:event_btnHienPassActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ThemNhanVienJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ThemNhanVienJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ThemNhanVienJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ThemNhanVienJframe.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ThemNhanVienJframe().setVisible(true);
			}
		});

	}

	private boolean kiemTraThongTin() {
		String ten = txtTenNV.getText();
		if (ten.equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(null, "<html><b>Tên nhân viên</b> không được bỏ trống!</html>");
			txtTenNV.requestFocus();
			return false;
		} else if (!ten.matches(
				"^([A-Za-zÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀẾỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴÝỶỸàáâãèéêìíòóôõùúăđĩũơưăạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ]*\\s*)+$")) {
			JOptionPane.showMessageDialog(this, "<html><b>Tên nhân viên</b> không được số và kí tự đặc biệt!</html>");
			txtTenNV.selectAll();
			txtTenNV.requestFocus();
			return false;

		}
		String cmnd = txtCMND.getText();
		if (cmnd.equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(null, "<html><b>Chứng minh nhân dân</b> không được bỏ trống!</html>");
			txtCMND.requestFocus();
			return false;
		} else if (!cmnd.matches("\\d{9}")) {
			JOptionPane.showMessageDialog(null, "<html><b>Chứng minh nhân dân</b> phải có <b>9</b> chữ số</html>");
			txtCMND.requestFocus();
			txtCMND.selectAll();
			return false;
		}
		String sdt = txtSDT.getText();
		if (sdt.equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(null, "<html><b>Số điện thoại</b> không được bỏ trống!</html>");
			txtSDT.requestFocus();
			return false;
		} else if (!sdt.matches(
				"(^(03)[2-9]\\d{7})|(^(07)[06-9]\\d{7})|(^(08)[1-5]\\d{7})|(^(056)\\d{7})|(^(058)\\d{7})|(^(059)\\d{7})|(^(09)[0-46-9]\\d{7})")) {
			JOptionPane.showMessageDialog(this,
					"<html><b>Số điện thoại</b> không có thực!<br>Vui lòng kiểm tra lại</html>");
			txtSDT.selectAll();
			txtSDT.requestFocus();
			return false;
		}
		if (jcbXa.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(null, "<html>Mời chọn <b>địa chỉ</b> của nhân viên!</html>");
			return false;
		}
		if (txtMatKhau.getPassword().toString().equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập mật khẩu");
			txtMatKhau.requestFocus();
			return false;
		}
		return true;
	}

	private void themNV() {
		if (!kiemTraThongTin())
			return;
		String ma = txtMaNV.getText();
		String ten = txtTenNV.getText().trim();
		String cmnd = txtCMND.getText();
		String sdt = txtSDT.getText();
		String mk = new String(txtMatKhau.getPassword());
		boolean gioiTinh = jcbGioiTinh.getSelectedItem().toString() == "Nam" ? true : false;
		boolean trangThai = true;
		boolean loaiNV = false;
		String tinh = jcbTinh.getSelectedItem().toString();
		String quan = jcbQuan.getSelectedItem().toString();
		String phuong = jcbXa.getSelectedItem().toString();
		if (btnQuanLy.isSelected())
			loaiNV = true;
		NhanVien n = new NhanVien(ten, ma, gioiTinh, sdt, mk, trangThai, loaiNV, cmnd, new DiaChi(tinh, quan, phuong));
		if (daoNV.themNV(n) == 1) {
			JOptionPane.showMessageDialog(null, "<html>Thêm thành công <b>" + ten + "</b></html>");
			dispose();
		} else if (daoNV.themNV(n) == -1) {
			JOptionPane.showMessageDialog(null,
					"<html>Số chứng minh này đã được dùng!<br>Vui lòng kiểm tra lại.</html>");
		} else if (daoNV.themNV(n) == -2) {
			JOptionPane.showMessageDialog(null,
					"<html>Số điện thoại này đã được dùng!<br>Vui lòng kiểm tra lại.</html>");
		}
	}

	@SuppressWarnings("unchecked")
	private void loadTinh() {
		vecTinhTP = daoDiaChi.getAllTinh();
		if (vecTinhTP.size() == 1) {
			JOptionPane.showMessageDialog(null, "Lỗi khi đọc danh sách tỉnh!");
			return;
		}
		DefaultComboBoxModel<String> md = new DefaultComboBoxModel<String>(vecTinhTP);
		jcbTinh.setModel(md);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup GroupLoai;
	private javax.swing.JLabel LBLCMND;
	private javax.swing.JButton btnHienPass;
	private javax.swing.JButton btnHuy;
	private javax.swing.JButton btnLamMoi;
	private javax.swing.JRadioButton btnNhanVien;
	private javax.swing.JRadioButton btnQuanLy;
	private javax.swing.JButton btnXacNhan;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JComboBox<String> jcbGioiTinh;
	private javax.swing.JComboBox<String> jcbQuan;
	private javax.swing.JLabel lblDC;
	private javax.swing.JLabel lblDC1;
	private javax.swing.JLabel lblMa;
	private javax.swing.JLabel lblMa1;
	private javax.swing.JLabel lblSDT1;
	private javax.swing.JLabel lblTen;
	private javax.swing.JLabel lblTitle;
	private javax.swing.JTextField txtCMND;
	private javax.swing.JTextField txtMaNV;
	private javax.swing.JPasswordField txtMatKhau;
	private javax.swing.JTextField txtSDT;
	private javax.swing.JTextField txtTenNV;
	// End of variables declaration//GEN-END:variables

}
